name: CD

on:
    push:
        branches:
            - develop

jobs:
    deploy:
        name: Deploy to Stage
        runs-on: ubuntu-latest
        steps:
            - run: curl "https://api.nsm.mosaiq.dev/deploy/${{ secrets.NSM_PROJECT_STAGE }}/${{ secrets.NSM_KEY_STAGE }}"
